---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  role_path: test/integration/roles/

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[cb_my_cron::default]
      - role[primary_box]
    attributes:
